# Курс "Python для анализа данных"

---
#3.2.5 Файловый ввод-вывод массивов

## Где мы сейчас?


<html>
 <head>
  <meta charset="utf-8">
 </head>
 <body>
  <ul>
    <li>1. Введение в анализ данных и разработку на языке Python </li> <!-2.1->
    <li>2. Основы языка </li> <!-2.1->
    <li>3. <strong>Библиотеки NumPy и SciPy для решения задач анализа данных и машинного обучения</strong> <i><- Вот в этой главе!</i>
     <ul>
      <li>3.1 Математические дисциплины в анализе данных и машинном обучении</li>      
      <li><strong>3.2 Основной объект NumPy ndarray</strong> <i><- Вот в этом параграфе!</i></li>
       <ul>
        <li>3.2.1 Быстрые поэлементные операции над массивами</li>
        <li>3.2.2 Индексирование и вырезание</li>
        <li>3.2.3 Уход от циклов: обработка данных с применением массивов</li>
        <li>3.2.4 Математические и статистические операции</li>
        <li><strong>3.2.5 Файловый ввод-вывод массивов</strong><i> <- Вот в этом пункте!</i></li>
       </ul>
      <li>3.3 Библиотека SciPy</li>
     </ul>
    </li>   
  </ul>
 </body>
</html>

## О чем будем говорить?


О том, как ```numpy``` сохраняет на диск и загружает данные с диска в текстовом или двоичном формате.

## Ключевые слова, понятия и выражения






*    ```np.save```   
*    ```np.load```
*    расширение ```*.npy```   

## Материал

### Хранение на диске в двоичном формате

In [ ]:
import numpy as np
arr = np.arange(10)
print('Сохраняем массив\n',arr,'\nв файл some_array.npy')

np.save('some_array', arr)

Сохраняем массив
 [0 1 2 3 4 5 6 7 8 9] 
в файл some_array.npy


In [ ]:
!ls

sample_data  some_array.npy


In [ ]:
new_arr = np.load('some_array.npy')
print('Считываем данные из файла some_array.npy:\n',new_arr)
print('Тип:', type(new_arr))

Считываем данные из файла some_array.npy:
 [0 1 2 3 4 5 6 7 8 9]
Тип: <class 'numpy.ndarray'>


In [ ]:
arr_a = np.arange(10)
arr_b = np.arange(10,20)
print('Сохраняем массивы\n',arr_a,'\n',arr_b,'\nв файл some_array_ab.npz')

np.savez('some_array_ab', a=arr_a, b = arr_b)

Сохраняем массивы
 [0 1 2 3 4 5 6 7 8 9] 
 [10 11 12 13 14 15 16 17 18 19] 
в файл some_array_ab.npz


In [ ]:
!ls

sample_data  some_array_ab.npz	some_array.npy


In [ ]:
new_arr = np.load('some_array_ab.npz')
print('Считываем данные из файла some_array_ab.npz:\n',new_arr['a'],new_arr['b'])
print('Тип:', type(new_arr))

Считываем данные из файла some_array_ab.npz:
 [0 1 2 3 4 5 6 7 8 9] [10 11 12 13 14 15 16 17 18 19]
Тип: <class 'numpy.lib.npyio.NpzFile'>


### Сохранение и загрузка текстовых файлов

In [ ]:
arr = np.arange(12).reshape(3,4)
print('Сохраняем массив\n',arr,'\nв файл some_array.txt')

np.savetxt('some_array.txt', arr, delimiter=';')

Сохраняем массив
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
в файл some_array.txt


In [ ]:
!ls

sample_data  some_array_ab.npz	some_array.npy	some_array.txt


In [ ]:
!cat some_array.txt

0.000000000000000000e+00;1.000000000000000000e+00;2.000000000000000000e+00;3.000000000000000000e+00
4.000000000000000000e+00;5.000000000000000000e+00;6.000000000000000000e+00;7.000000000000000000e+00
8.000000000000000000e+00;9.000000000000000000e+00;1.000000000000000000e+01;1.100000000000000000e+01


In [ ]:
new_arr = np.loadtxt('some_array.txt', delimiter=';')
print('Считываем данные из файла some_array.txt:\n',new_arr)
print('Тип:', type(new_arr))
print('Размер:', new_arr.shape)

Считываем данные из файла some_array.txt:
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
Тип: <class 'numpy.ndarray'>
Размер: (3, 4)


## Дополнительные материалы и литература



*   Уэс Маккинли, Python и анализ данных/ Пер. с англ. Слинкин А. А. - М.: ДМК Пресс, 2015. - 482 с.: ил. C. 119