# Курс "Python для анализа данных"

---
#3.2.3 Уход от циклов: обработка данных с применением массивов

## Где мы сейчас?


<html>
 <head>
  <meta charset="utf-8">
 </head>
 <body>
  <ul>
    <li>1. Введение в анализ данных и разработку на языке Python </li> <!-2.1->
    <li>2. Основы языка </li> <!-2.1->
    <li>3. <strong>Библиотеки NumPy и SciPy для решения задач анализа данных и машинного обучения</strong> <i><- Вот в этой главе!</i>
     <ul>
      <li>3.1 Математические дисциплины в анализе данных и машинном обучении</li>      
      <li><strong>3.2 Основной объект NumPy ndarray</strong> <i><- Вот в этом параграфе!</i></li>
       <ul>
        <li>3.2.1 Быстрые поэлементные операции над массивами</li>
        <li>3.2.2 Индексирование и вырезание</li>
        <li><strong>3.2.3 Уход от циклов: обработка данных с применением массивов</strong><i> <- Вот в этом пункте!</i></li>
        <li>3.2.4 Математические и статистические операции</li>
        <li>3.2.5 Файловый ввод-вывод массивов</li>
       </ul>
      <li>3.3 Библиотека SciPy</li>
     </ul>
    </li>   
  </ul>
 </body>
</html>

## О чем будем говорить?


О встороенных методах переиндексации массивов ```ndarray``` и манипулировании с векторными представлениями данных без использования циклов.

## Ключевые слова, понятия и выражения






*   переиндексация
*   изменение размеров

## Материал

### Изменение формы массивов ```ndarray```

Материал опирается на [статью](https://proglib.io/p/illyustrirovannoe-rukovodstvo-po-izmeneniyu-formy-mnogomernyh-massivov-numpy-2020-01-12) с proglib.io.

#### Изменение формы массива с помощью метода ```reshape()```

In [0]:
import numpy as np

a1 = np.arange(1, 13)  # числа от 1 до 12
print('Исходный массив:')
print(a1.shape)
print(a1)

Исходный массив:
(12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [0]:
a1_2d = a1.reshape(3, 4)
print('Двумерный массив после преобразования размера:')
print(a1_2d.shape)
print(a1_2d)

print('Двумерный массив с автоматическим вычислением размера:')
a1_2d = a1.reshape(3, -1)
print(a1_2d.shape)
print(a1_2d)

Двумерный массив после преобразования размера:
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Двумерный массив с автоматическим вычислением размера:
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [0]:
print('Изменение формы по направлению:')
print('* как в C:')
print(a1.reshape(3, 4, order='C'))
print('* как в Fortran:')
print(a1.reshape(3, 4, order='F'))

Изменение формы по направлению:
* как в C:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
* как в Fortran:
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [0]:
print('Преобразование одномерного массива в двумерный:')
print('до')
print(a1)
print(a1.shape)

print('после')
print(a1.reshape(1,-1))
print(a1.reshape(1,-1).shape)

Преобразование одномерного массива в двумерный:
до
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
после
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
(1, 12)


#### Схлопование массива в одномерный методом ```ravel()```

In [0]:
print('Исходный массив:')
print(a1_2d)

print('Схлопываем строка за строкой:')
print(a1_2d.ravel()) 

print('Схлопываем столбец за столбцом:')
print(a1_2d.ravel(order='F')) 

Исходный массив:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Схлопываем строка за строкой:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Схлопываем столбец за столбцом:
[ 1  5  9  2  6 10  3  7 11  4  8 12]


#### Конкатенация массивов методами ```stack()``` и ```hstack()```

![alt text](https://drive.google.com/uc?id=1vIq1Qn3_ZiJ7P0hIS0jjRkQ18_mKo3Co)

In [0]:
a1 = np.arange(1, 13)
print('Массив 1:')
print(a1)
print('Массив 2:')
a2 = np.arange(13, 25)
print(a2)

print('Горизонтальная конкатенация:')
print(np.hstack((a1, a2)))
print(np.stack((a1, a2)))
print('Вертикальныя конкатенация:')
print(np.stack((a1, a2), axis=1))

Массив 1:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Массив 2:
[13 14 15 16 17 18 19 20 21 22 23 24]
Горизонтальная конкатенация:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
Вертикальныя конкатенация:
[[ 1 13]
 [ 2 14]
 [ 3 15]
 [ 4 16]
 [ 5 17]
 [ 6 18]
 [ 7 19]
 [ 8 20]
 [ 9 21]
 [10 22]
 [11 23]
 [12 24]]


#### Объединение двумерных массивов в трехмерный

![alt text](https://drive.google.com/uc?id=1XMAVpMKVmI6665VDIrFwcvUla0_Ps5Wb)

In [0]:
a1 = np.arange(1, 13).reshape(3, -1)
print('Массив 1:')
print(a1)
print('Массив 2:')
a2 = np.arange(13, 25).reshape(3, -1)
print(a2)

Массив 1:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Массив 2:
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [0]:
print('Соединение по оси 0:')
a3_0 = np.stack((a1, a2))
print(a3_0)
print('Размер:', a3_0.shape)

print('Соединение по оси 1:')
a3_1 = np.stack((a1, a2), axis=1)
print(a3_1)
print('Размер:', a3_1.shape)

print('Соединение по оси 2:')
a3_2 = np.stack((a1, a2), axis=2)
print(a3_2)
print('Размер:', a3_2.shape)

Соединение по оси 0:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Размер: (2, 3, 4)
Соединение по оси 1:
[[[ 1  2  3  4]
  [13 14 15 16]]

 [[ 5  6  7  8]
  [17 18 19 20]]

 [[ 9 10 11 12]
  [21 22 23 24]]]
Размер: (3, 2, 4)
Соединение по оси 2:
[[[ 1 13]
  [ 2 14]
  [ 3 15]
  [ 4 16]]

 [[ 5 17]
  [ 6 18]
  [ 7 19]
  [ 8 20]]

 [[ 9 21]
  [10 22]
  [11 23]
  [12 24]]]
Размер: (3, 4, 2)


#### Схлопование многомерного массива в одномерный методом ```ravel()```

In [0]:
print(a3_0)
print(a3_0.ravel())

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


### Векторизация

Векторизация - замена явных циклов выраже­ниями-массивами.

In [0]:
points = np.arange(-5, 5, 1) # 1000 equally spaced points
xs, ys = np.meshgrid(points, points)
print(xs)
print(ys)

[[-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]]
[[-5 -5 -5 -5 -5 -5 -5 -5 -5 -5]
 [-4 -4 -4 -4 -4 -4 -4 -4 -4 -4]
 [-3 -3 -3 -3 -3 -3 -3 -3 -3 -3]
 [-2 -2 -2 -2 -2 -2 -2 -2 -2 -2]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 2  2  2  2  2  2  2  2  2  2]
 [ 3  3  3  3  3  3  3  3  3  3]
 [ 4  4  4  4  4  4  4  4  4  4]]


In [0]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

array([[7.07106781, 6.40312424, 5.83095189, 5.38516481, 5.09901951,
        5.        , 5.09901951, 5.38516481, 5.83095189, 6.40312424],
       [6.40312424, 5.65685425, 5.        , 4.47213595, 4.12310563,
        4.        , 4.12310563, 4.47213595, 5.        , 5.65685425],
       [5.83095189, 5.        , 4.24264069, 3.60555128, 3.16227766,
        3.        , 3.16227766, 3.60555128, 4.24264069, 5.        ],
       [5.38516481, 4.47213595, 3.60555128, 2.82842712, 2.23606798,
        2.        , 2.23606798, 2.82842712, 3.60555128, 4.47213595],
       [5.09901951, 4.12310563, 3.16227766, 2.23606798, 1.41421356,
        1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [5.        , 4.        , 3.        , 2.        , 1.        ,
        0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.09901951, 4.12310563, 3.16227766, 2.23606798, 1.41421356,
        1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [5.38516481, 4.47213595, 3.6055512

### Укладывание

Укладывание - это способ выполнения арифметических операций над массивами разной формы.

![alt text](https://drive.google.com/uc?id=14bWKPgrAAIzMyIEoAMtye3addSkVYuVL)

In [0]:
arr = np.arange(12)
print(arr)
print(arr * 4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  4  8 12 16 20 24 28 32 36 40 44]


In [0]:
arr0 = np.arange(4)
arr = np.stack((arr0,arr0,arr0),axis=1)

vec = np.array([1,2,3])

print('Изначальная матрица:')
print(arr)
print('Вектор для суммирования:')
print(vec)

print('Результат суммирования:')
print(arr + vec)

Изначальная матрица:
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]
Вектор для суммирования:
[1 2 3]
Результат суммирования:
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [0]:
arr = np.random.randn(4, 3)
print('Изначальная матрица:')
print(arr)

print('Средние значения по столбцам:')
print(arr.mean(0))

print('Центрированные значения в столбцах:')
demeaned = arr - arr.mean(0)
print(demeaned)

print('Средние значения по столбцам в центированной матрице:')
print(demeaned.mean(0))

Изначальная матрица:
[[-0.32581552 -0.13240649 -0.37831171]
 [-0.43855863 -0.24346432  1.215288  ]
 [ 1.30997662 -1.35880339 -2.09070716]
 [ 1.00515751  0.29292912 -0.50482256]]
Средние значения по столбцам:
[ 0.38769    -0.36043627 -0.43963836]
Центрированные значения в столбцах:
[[-0.71350551  0.22802978  0.06132665]
 [-0.82624863  0.11697195  1.65492636]
 [ 0.92228663 -0.99836712 -1.65106881]
 [ 0.61746752  0.65336539 -0.0651842 ]]
Средние значения по столбцам в центированной матрице:
[ 5.55111512e-17 -2.77555756e-17 -2.77555756e-17]


## Дополнительные материалы и литература



*   Уэс Маккинли, Python и анализ данных/ Пер. с англ. Слинкин А. А. - М.: ДМК Пресс, 2015. - 482 с.: ил. C. 112