# Курс "Python для анализа данных"

---
#3.2.1 Быстрые поэлементные операции над массивами

## Где мы сейчас?


<html>
 <head>
  <meta charset="utf-8">
 </head>
 <body>
  <ul>
    <li>1. Введение в анализ данных и разработку на языке Python </li> <!-2.1->
    <li>2. Основы языка </li> <!-2.1->
    <li>3. <strong>Библиотеки NumPy и SciPy для решения задач анализа данных и машинного обучения</strong> <i><- Вот в этой главе!</i>
     <ul>
      <li>3.1 Математические дисциплины в анализе данных и машинном обучении</li>      
      <li><strong>3.2 Основной объект NumPy ndarray</strong> <i><- Вот в этом параграфе!</i></li>
       <ul>
        <li><strong>3.2.1 Быстрые поэлементные операции над массивами</strong><i> <- Вот в этом пункте!</i></li>
        <li>3.2.2 Индексирование и вырезание</li>
        <li>3.2.3 Уход от циклов: обработка данных с применением массивов</li>
        <li>3.2.4 Математические и статистические операции</li>
        <li>3.2.5 Файловый ввод-вывод массивов</li>
       </ul>
      <li>3.3 Библиотека SciPy</li>
     </ul>
    </li>   
  </ul>
 </body>
</html>

## О чем будем говорить?


О базовом и самом главном элементе библиотеки NumPy для представле­ния N-мерного массива, быстром и гибком контейнере для хранения больших наборов однородных данных в Python, а именно объекте ndarray.

## Ключевые слова, понятия и выражения






*   объект ```ndarray```

## Материал

### Базовый пример ```ndarray```

ndarray - это обобщенный многомерный контейнер для однородных данных,
т. е. в нем могут храниться только элементы одного типа.

In [0]:
import numpy as np

data = np.array([[1.0, 2.0, 3.0],
                [4.0, 5.0, 7.0]])

print('Тип объекта data: ',type(data))
print('Тип элементов объекта data:', data.dtype)
print('Размер объекта data:', data.shape)

Тип объекта data:  <class 'numpy.ndarray'>
Тип элементов объекта data: float64
Размер объекта data: (2, 3)


### Создание ndarray

Функции создания массива ndarray:

![alt text](https://drive.google.com/uc?id=1x1-pFEatUPospJm0LG4hLSEB85KcP5EI)

In [0]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [0]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [0]:
print('Размерность arr2:', arr2.ndim)
print('Размер arr2:', arr2.shape)

Размерность arr2: 2
Размер arr2: (2, 4)


In [0]:
print('Тип arr1:', arr1.dtype)
print('Тип arr2:', arr2.dtype)

Тип arr1: float64
Тип arr2: int64


In [0]:
print('Массивы из всех нулей:')
print("*"*30)
print(np.zeros(10))
print("*"*30)
print(np.zeros((3, 6)))

Массивы из всех нулей:
******************************
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
******************************
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [0]:
np.empty((2, 3, 2))

array([[[2.70190984e-316, 2.32210854e-322],
        [0.00000000e+000, 0.00000000e+000],
        [6.90285231e-310, 1.16095484e-028]],

       [[4.50606156e-144, 1.05786746e+214],
        [7.59699731e-096, 6.03461190e+151],
        [1.33819343e+253, 2.66090406e-312]]])

In [0]:
print('Подобие функции range:')
print(np.arange(15))

Подобие функции range:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


### Тип данных для ```ndarray```

![alt text](https://drive.google.com/uc?id=1laOM-l8KmPfr3IAHDrj5i-G9hpf3qltv)

In [0]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print('Тип массива arr1:', arr1.dtype)
print('Тип массива arr2:', arr2.dtype)

Тип массива arr1: float64
Тип массива arr2: int32


In [0]:
print('Преобразование типов данных:')
arr = np.array([1, 2, 3, 4, 5])
print('до',arr.dtype)

float_arr = arr.astype(np.float64)
print('после',float_arr.dtype)

Преобразование типов данных:
до int64
после float64


In [0]:
print('Преобразование типов данных:')

arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print('Исходный массив типа', arr.dtype)
print(arr)

print('Массив типа int32')
print(arr.astype(np.int32))

print('Массив типа string_')
print(arr.astype(np.string_))

Преобразование типов данных:
Исходный массив типа float64
[ 3.7 -1.2 -2.6  0.5 12.9 10.1]
Массив типа int32
[ 3 -1 -2  0 12 10]
Массив типа string_
[b'3.7' b'-1.2' b'-2.6' b'0.5' b'12.9' b'10.1']


### Операции между массивами и скалярами

In [0]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[4., 5., 6.], [1., 2., 3.]])
print('Арифметические операции между массивами:')
print(arr1)
print(arr2)

print('*'*30)
print('Поэлементное умножение:')
print(arr1 * arr2)

print('*'*30)
print('Поэлементное деление:')
print(arr1/arr2)

print('*'*30)
print('Поэлементное сложение:')
print(arr1 + arr2)

print('*'*30)
print('Поэлементная разность:')
print(arr1 - arr2)

Арифметические операции между массивами:
[[1. 2. 3.]
 [4. 5. 6.]]
[[4. 5. 6.]
 [1. 2. 3.]]
******************************
Поэлементное умножение:
[[ 4. 10. 18.]
 [ 4. 10. 18.]]
******************************
Поэлементное деление:
[[0.25 0.4  0.5 ]
 [4.   2.5  2.  ]]
******************************
Поэлементное сложение:
[[5. 7. 9.]
 [5. 7. 9.]]
******************************
Поэлементная разность:
[[-3. -3. -3.]
 [ 3.  3.  3.]]


In [0]:
print('Поэлементное сравнение элементов массивов:')
print(arr1 > arr2)

Поэлементное сравнение элементов массивов:
[[False False False]
 [ True  True  True]]


In [0]:
print('Операция со скалярами:')
print(arr1 * 5)
print(arr1 / 5)
print(arr1 + 5)
print(arr1 - 5)

Операция со скалярами:
[[ 5. 10. 15.]
 [20. 25. 30.]]
[[0.2 0.4 0.6]
 [0.8 1.  1.2]]
[[ 6.  7.  8.]
 [ 9. 10. 11.]]
[[-4. -3. -2.]
 [-1.  0.  1.]]


### Быстрые поэлементарные операции над массивами

Бинарные функции

![alt text](https://drive.google.com/uc?id=1fjUKRouIuFOY_whkBmZIww0SgodA8UEN)

Унарные функции

![alt text](https://drive.google.com/uc?id=13mdlDmD4DOWOvCQyM2wxPJvKEiURGi8H)

In [0]:
arr = np.arange(10)
print('Возведение в квадрат всех элементов массива:')
print(arr)
print(np.sqrt(arr))

Возведение в квадрат всех элементов массива:
[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [0]:
arr = [1.3, 1.2, 2.0, np.nan, 3.0, 1.0]
print('Проверка на наличие нечислового значения NaN в массиве:')
print(arr)
print(np.isnan(arr))

Проверка на наличие нечислового значения NaN в массиве:
[1.3, 1.2, 2.0, nan, 3.0, 1.0]
[False False False  True False False]


## Дополнительные материалы и литература



*   Уэс Маккинли, Python и анализ данных/ Пер. с англ. Слинкин А. А. - М.: ДМК Пресс, 2015. - 482 с.: ил. C. 93