# Курс "Python для анализа данных"

---
#3.2.4 Математические и статистические операции


## Где мы сейчас?


<html>
 <head>
  <meta charset="utf-8">
 </head>
 <body>
  <ul>
    <li>1. Введение в анализ данных и разработку на языке Python </li> <!-2.1->
    <li>2. Основы языка </li> <!-2.1->
    <li>3. <strong>Библиотеки NumPy и SciPy для решения задач анализа данных и машинного обучения</strong> <i><- Вот в этой главе!</i>
     <ul>
      <li>3.1 Математические дисциплины в анализе данных и машинном обучении</li>      
      <li><strong>3.2 Основной объект NumPy ndarray</strong> <i><- Вот в этом параграфе!</i></li>
       <ul>
        <li>3.2.1 Быстрые поэлементные операции над массивами</li>
        <li>3.2.2 Индексирование и вырезание</li>
        <li>3.2.3 Уход от циклов: обработка данных с применением массивов</li>
        <li><strong>3.2.4 Математические и статистические операции</strong><i> <- Вот в этом пункте!</i></li>
        <li>3.2.5 Файловый ввод-вывод массивов</li>
       </ul>
      <li>3.3 Библиотека SciPy</li>
     </ul>
    </li>   
  </ul>
 </body>
</html>

## О чем будем говорить?


О функциях ```NumPy```, позволяющих вычислять статистики массивов ```ndarray```в целом или вдоль одной оси. Также поговорим о функциях, которые позволяют решать задачи линейной алгебры и теории вероятностей.

## Ключевые слова, понятия и выражения






*   ```sum()```, ```std()```, ```mean()```
*   транспонирование
*   матричное умножение
*   генерация случайных чисел

## Материал

### Математические и статистические методы

![alt text](https://drive.google.com/uc?id=1XvWjo9XCAS-CqSs0qKtrU-rZ4boW155k)

In [0]:
import numpy as np

arr = np.random.randn(5, 4)
print('Исходная матрица\n', arr)
print('Среднее значение', arr.mean())
print('Среднее значение', np.mean(arr))
print('Сумма элементов', arr.sum())

Исходная матрица
 [[ 0.52860787 -1.02747625 -0.27946906  0.75358208]
 [-0.43146672 -0.10254044  0.91717433  0.3899317 ]
 [ 0.43689319 -0.09629962  1.53339129 -1.51149779]
 [ 0.28165691 -0.757956   -1.06177232  0.55057446]
 [ 0.58612626 -1.35837354  0.03571287 -1.63623133]]
Среднее значение -0.11247160518632
Среднее значение -0.11247160518632
Сумма элементов -2.2494321037264


In [0]:
print('Среднее значение по строкам', arr.mean(axis=1))
print('Среднее значение по столбцам', arr.mean(axis=0))
print('Сумма значений по столбцам', arr.sum(axis=0))
print('Сумма значений по строкам', arr.sum(axis=1))

Среднее значение по строкам [-0.00618884  0.19327471  0.09062177 -0.24687424 -0.59319143]
Среднее значение по столбцам [ 0.2803635  -0.66852917  0.22900742 -0.29072817]
Сумма значений по столбцам [ 1.40181751 -3.34264586  1.14503712 -1.45364087]
Сумма значений по строкам [-0.02475535  0.77309886  0.36248708 -0.98749695 -2.37276574]


In [0]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
print('Исходный массив:', arr)
print('Сумма с промежуточными результатами:', arr.cumsum())

Исходный массив: [0 1 2 3 4 5 6 7]
Сумма с промежуточными результатами: [ 0  1  3  6 10 15 21 28]


In [0]:
print('Индекс максимального элемента массива:', arr.argmax())

Индекс максимального элемента массива: 7


### Методы булевых массивов

In [0]:
arr = np.random.randn(5, 4)
print('Исходная матрица\n', arr)

print('Количество положительных значений:',(arr>0).sum())

Исходная матрица
 [[ 0.14985978 -0.20548681  0.97504743 -0.22703155]
 [ 1.14831777  0.28229171 -1.07878193  0.99395241]
 [-2.30359432 -0.3511886   0.61159009  0.31863064]
 [-0.3324795  -0.57310043 -0.41103013 -1.70737839]
 [-0.931477   -0.51110021  1.12233282 -0.19503009]]
Количество положительных значений: 8


In [0]:
bool_arr = np.array([True, False, False])
print('Все True:', bool_arr.all())
print('Хотя бы один True:', bool_arr.any())

Все True: False
Хотя бы один True: True


### Теоретико-множественные операции

![alt text](https://drive.google.com/uc?id=1ziuzpdxlN4tPQwVBk0ij2GFN_0PK37hu)

In [0]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

### Линейная алгебра

![alt text](https://drive.google.com/uc?id=1gpvES_c1py_Ww3JKYq7v-HWidLp468pl)

In [0]:
A = np.array([[1., 2., 3.], [4., 5., 6.]])
B = np.array([[6., 23.], [-1, 7], [8, 9]])
print('Матрица A')
print(A)
print('Матрица B')
print(B)

print('Произведение матриц A*B')
print(A.dot(B))

print('Произведение матриц A*B')
print(np.dot(A, B))

print('Произведение матриц A*B')
print(A @ B)

Матрица A
[[1. 2. 3.]
 [4. 5. 6.]]
Матрица B
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]
Произведение матриц A*B
[[ 28.  64.]
 [ 67. 181.]]
Произведение матриц A*B
[[ 28.  64.]
 [ 67. 181.]]
Произведение матриц A*B
[[ 28.  64.]
 [ 67. 181.]]


In [0]:
X = np.random.randn(5, 5)
print('Исходная матрица:')
print(X)

mat = X.T.dot(X)
print('Матрица Xtr*X:')
print(mat)

Исходная матрица:
[[-0.91780585 -0.05096368  0.83205348  0.65824526  1.3111014 ]
 [-1.17915452  0.21130346 -1.63801762 -0.30460216 -0.44311461]
 [-1.33053169  1.29285586 -0.88715365  0.22004652 -0.11119398]
 [ 0.39665679 -0.28932308  0.27459522  0.68973992 -1.86490823]
 [ 0.38327062 -0.19470529 -1.63821909 -0.83314364 -0.26576479]]
Матрица Xtr*X:
[[ 4.3073205  -2.11195714  1.82923719 -0.58347665 -1.37447719]
 [-2.11195714  1.84034072 -1.2959619   0.14923814  0.28709882]
 [ 1.82923719 -1.2959619   6.92162064  2.40569499  1.83866824]
 [-0.58347665  0.14923814  2.40569499  1.74435924 -0.0913493 ]
 [-1.37447719  0.28709882  1.83866824 -0.0913493   5.47621518]]


In [0]:
print('Обратная матрица для Xtr*X:')
print(np.linalg.inv(mat))

Обратная матрица для Xtr*X:
[[ 3.47841638  0.9282259  -3.25161988  5.67379511  2.01077907]
 [ 0.9282259   1.33473203 -0.26475324  0.57511509  0.26148627]
 [-3.25161988 -0.26475324  3.71907132 -6.30698471 -2.15615048]
 [ 5.67379511  0.57511509 -6.30698471 11.31383599  3.70024733]
 [ 2.01077907  0.26148627 -2.15615048  3.70024733  1.45924835]]


In [0]:
print('(Xtr*X)*(Xtr*X)^(-1):')
print(mat.dot(np.linalg.inv(mat)))

(Xtr*X)*(Xtr*X)^(-1):
[[ 1.00000000e+00  1.18759825e-16  6.96708909e-16 -1.68279231e-15
  -1.32062042e-15]
 [-1.02035469e-15  1.00000000e+00 -5.94533270e-16  1.81057247e-16
   1.47787604e-15]
 [ 2.21664328e-15 -1.78215277e-16  1.00000000e+00 -6.30554814e-16
  -1.51682746e-15]
 [ 3.51465268e-16 -1.53291426e-16  1.36662373e-16  1.00000000e+00
  -1.29402078e-15]
 [-2.18101216e-15 -8.73538493e-17 -1.57878072e-15  7.67822159e-16
   1.00000000e+00]]


In [0]:
s,v,d = np.linalg.svd(mat)
s

array([[-0.30327652, -0.62313346, -0.4391579 , -0.40685819,  0.40166502],
       [ 0.22022114,  0.29602753,  0.29403985, -0.87994869,  0.05568857],
       [-0.8489024 ,  0.03577149,  0.26786638, -0.13829059, -0.43267591],
       [-0.24194282,  0.08357476,  0.55846583,  0.20244446,  0.76263431],
       [-0.28346851,  0.71819778, -0.58055527, -0.00697622,  0.25834951]])

### Генерация случайных чисел

![alt text](https://drive.google.com/uc?id=1Z36qj4Pxk_kITNINUFzXl03sZwyr7NEP)

In [0]:
samples = np.random.normal(size=(4, 4))
samples

array([[ 1.05546473, -0.46636013, -2.52191743,  1.29382948],
       [ 0.48556524, -0.72167852, -1.28813533, -0.54316216],
       [ 1.34106697,  0.42896088, -0.73745716, -0.44054361],
       [ 0.0587648 , -0.51699792, -1.01848425, -0.16325273]])

In [0]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]
%timeit np.random.normal(size=N)

1 loop, best of 3: 675 ms per loop
10 loops, best of 3: 43.4 ms per loop


## Дополнительные материалы и литература



*   Уэс Маккинли, Python и анализ данных/ Пер. с англ. Слинкин А. А. - М.: ДМК Пресс, 2015. - 482 с.: ил. C. 115