# Курс "Python для анализа данных"

---
#3.3.2 Решение некоторых задач линейной алгебры

## Где мы сейчас?


<html>
 <head>
  <meta charset="utf-8">
 </head>
 <body>
  <ul>
    <li>1. Введение в анализ данных и разработку на языке Python </li> <!-2.1->
    <li>2. Основы языка </li> <!-2.1->
    <li>3. <strong>Библиотеки NumPy и SciPy для решения задач анализа данных и машинного обучения</strong> <i><- Вот в этой главе!</i>
     <ul>
      <li>3.1 Математические дисциплины в анализе данных и машинном обучении</li>      
      <li>3.2 Основной объект NumPy ndarray</li>
      <li><strong>3.3 Библиотека SciPy</strong> <i><- Вот в этом параграфе!</i></li>
       <ul>
        <li>3.3.1 Обзор основных пакетов библиотеки SciPy</li>
        <li><strong>3.3.2 Решение некоторых задач линейной алгебры</strong><i> <- Вот в этом пункте!</i></li>
        <li>3.3.3 Решение некоторых задач математической статистики</li>
        <li>3.3.4 Решение некоторых задач математического анализа</li>
        <li>3.3.5 Решение специальных задач из области анализа данных и машинного обучения</li>
       </ul>
     </ul>
    </li>   
  </ul>
 </body>
</html>







## О чем будем говорить?


О том, почему так важно владеть методами линейной алгебры для анализа данных и машинного обучения, а также о модулях библиотеки ```SciPy```, которые реализуют указанные методы.

## Ключевые слова, понятия и выражения






*   вектор
*   матрица
*   система уравнений
*   разложение матриц
*   ```scipy.linalg```   

## Материал

### Примеры практического использования линейной алгебры в анализе данных и машинном обучении



*   нахождение ошибки предсказания модели, то есть разность векторов ожидаемого прогноза и полученного с использованием модели (операции с векторами)
*   регуляризация - проблема "запоминания" моделью обучающих данных, а не выявление обобщений и  закономерностей (использование весовых коэффициентов и их норм)
*   классификация объектов с использованием метода опорных векторов (понятие расстояния от точки до гиперплоскости)
*   уменьшение размерности исходных данных с использованием метода главных компонент (собственные вектора и собственные значения матрицы)
*   рекомендательные системы и понижение размерности(сингулярные разложения)
*   векторное представление слов Word Embedding 
*   глубокое обучение (тензоры и операции над ними)

#### Вектора, матрицы и тензоры

In [ ]:
import numpy as np

b = np.mat('[5 6]')
print('Вектор:\n',b)

A = np.mat('[1 2;3 4]')
print('Матрица:\n',A)
print('Транспонированная матрица:\n', A.T)

print('Сумма матриц:\n',A + A.T)
print('Умножение вектора на матрицу:\n', b*A)
print('Умножение матриц:\n', A * A.T)

Вектор:
 [[5 6]]
Матрица:
 [[1 2]
 [3 4]]
Транспонированная матрица:
 [[1 3]
 [2 4]]
Сумма матриц:
 [[2 5]
 [5 8]]
Умножение вектора на матрицу:
 [[23 34]]
Умножение матриц:
 [[ 5 11]
 [11 25]]


#### Нахождение обратной матрицы

![alt text](https://drive.google.com/uc?id=1tGXvrJ2ODkZ58p_HnHlKLojheagLiquU)

In [ ]:
from scipy import linalg
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
print('Матрица:\n',A)
print('Обратная ей матрица:\n',linalg.inv(A))
print('Проверка:\n', A.dot(linalg.inv(A)))

Матрица:
 [[1 3 5]
 [2 5 1]
 [2 3 8]]
Обратная ей матрица:
 [[-1.48  0.36  0.88]
 [ 0.56  0.08 -0.36]
 [ 0.16 -0.12  0.04]]
Проверка:
 [[ 1.00000000e+00 -1.11022302e-16  4.85722573e-17]
 [ 3.05311332e-16  1.00000000e+00  7.63278329e-17]
 [ 2.22044605e-16 -1.11022302e-16  1.00000000e+00]]


#### Вычисление нормы

![alt text](https://drive.google.com/uc?id=1l7ZUX_FmxjY1i8DOa0t_7vDW7RiXwotC)

In [ ]:
x = np.array([2, 1, -2,4])
print('Вектор:\n', x)
print('L1 норма: ', linalg.norm(x,1))
print('L2 норма: ', linalg.norm(x,2))

Вектор:
 [ 2  1 -2  4]
L1 норма:  9.0
L2 норма:  5.0


#### Решение систем линейных уравнений

![alt text](https://drive.google.com/uc?id=1JOCF10g_2uzc1Wmx26v2UYioGlVt1Tub)

![alt text](https://drive.google.com/uc?id=1cxt2oMqzCmoSfEgyhzs2GkcUArEnSSbG)

In [ ]:
A = np.array([[1,3,5],
              [2,5,1],
              [2,3,8]])
b = np.array([[10],[8],[3]])

print('Уравнения:')
print(A)
print('*')
print('[x,\ny,\nz]')
print('=')
print(b)

print('Решение уравнения:')
print('[x,\ny,\nz]')
print('=')
print(np.linalg.solve(A, b))

print('Решение уравнения:')
print('[x,\ny,\nz]')
print('=')
print(linalg.inv(A).dot(b))

Уравнения:
[[1 3 5]
 [2 5 1]
 [2 3 8]]
*
[x,
y,
z]
=
[[10]
 [ 8]
 [ 3]]
Решение уравнения:
[x,
y,
z]
=
[[-9.28]
 [ 5.16]
 [ 0.76]]
Решение уравнения:
[x,
y,
z]
=
[[-9.28]
 [ 5.16]
 [ 0.76]]


#### Собственные вектора и собственные значения

![alt text](https://drive.google.com/uc?id=14krANqspWHmwopQa3TAazrmskJckd003)

![alt text](https://drive.google.com/uc?id=1ijarYtFFM-lRUgxf4u9h83CIul75swT-)

![alt text](https://drive.google.com/uc?id=1rKrUgVoT3oGEPbbZPGNDL_OFo2BIq2ar)

In [ ]:
A = np.array([[1,5,2],
              [2,4,1],
              [3,6,2]])

la, v = linalg.eig(A)
print('Собственные вектора:\n',v)
print('Собственные значения:', la)

print('Проверка вектора',v[:,0].T)
print('С собственным значением',la[0])
print(A.dot(v[:,0].T))
print(la[0]*v[:,0])

Собственные вектора:
 [[-0.5297175  -0.90730751  0.28380519]
 [-0.44941741  0.28662547 -0.39012063]
 [-0.71932146  0.30763439  0.87593408]]
Собственные значения: [ 7.9579162 +0.j -1.25766471+0.j  0.2997485 +0.j]
Проверка вектора [-0.5297175  -0.44941741 -0.71932146]
С собственным значением (7.957916204910748+0j)
[-4.21544748 -3.57642611 -5.72429989]
[-4.21544748+0.j -3.57642611+0.j -5.72429989+0.j]


#### Матричное разложение

Пример разложения SVD(Singular value decomposition):

![alt text](https://drive.google.com/uc?id=1-kaA8P7TIUqcvfCrqfHPEnDBKg0HO2h6)

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
print('Матрица:\n',A)
M,N = A.shape
U,s,Vh = linalg.svd(A)
Sig = linalg.diagsvd(s,M,N)
print('Матрица U:\n',U)
print('Матрица sigma:\n',Sig)
print('Матрица Vh:\n',Vh)
print('Проверка:\n', U.dot(Sig.dot(Vh)))

Матрица:
 [[1 2 3]
 [4 5 6]]
Матрица U:
 [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]
Матрица sigma:
 [[9.508032   0.         0.        ]
 [0.         0.77286964 0.        ]]
Матрица Vh:
 [[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]
Проверка:
 [[1. 2. 3.]
 [4. 5. 6.]]


## Дополнительные материалы и литература



*   https://docs.scipy.org/doc/scipy/reference/tutorial/linalg.html