# Курс "Python для анализа данных"

---
#4.1.2 Применение функций и отображений, арифметические операции и выравнивание данных


## Где мы сейчас?


<html>
 <head>
  <meta charset="utf-8">
 </head>
 <body>
  <ul>
    <li>1. Введение в анализ данных и разработку на языке Python </li> <!-2.1->
    <li>2. Основы языка </li> <!-2.1->
    <li>3. Библиотеки NumPy и SciPy для решения задач анализа данных и машинного обучения </li> <!-2.1->
    <li>4. <strong>Библиотека Pandas для работы с высокоуровневыми структурами данных</strong> <i><- Вот в этой главе!</i>
     <ul>
      <li><strong>4.1 Введение в структуры данных Pandas</strong> <i><- Вот в этом параграфе!</i></li>
       <ul>
        <li>4.1.1 Работа с объектами Series, DataFrame. Переиндексация, доступ по индексу, выборка, фильтрация</li>
        <li><strong>4.1.2 Применение функций и отображений, арифметические операции и выравнивание данных</strong><i> <- Вот в этом пункте!</i></li>
        <li>4.1.3 Редукция и вычисление описательных статистик. Обработка отсутствующих данных</li>
        <li>4.1.4 Иерархическое индексирование</li>
       </ul>
      <li>4.2 Переформатирование данных: очистка, преобразование, слияние, изменение формы</li>
     </ul>
    </li>   
  </ul>
 </body>
</html>

## О чем будем говорить?


Об арифметических операциях между массивами ```DataFrame``` и ```Series``` и выравнивании данных при этом. Уделим внимание применению функций к указанным типам массивов.  

## Ключевые слова, понятия и выражения






*   ```pandas```
*   ```DataFrame```
*   ```Series```
*   ```apply```
*   ```map```

## Материал

### Арифметические операции и выравнивание данных

![alt text](https://drive.google.com/uc?id=1Vrk78MJUjkOLGWnHL0zAgtC8k2XF1pB5)

In [ ]:
import pandas as pd
import numpy as np

print('Пример арифметических операций с Series и выравнивание:')
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])
print(s1)
print(s2)
print(s1 + s2)

Пример арифметических операций с Series и выравнивание:
a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64
a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64
a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64


In [ ]:
print('Пример арифметических операций с DataFrame и выравнивание:')

df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
print(df1)
print(df2)
print(df1 + df2)

Пример арифметических операций с DataFrame и выравнивание:
            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0
          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN


In [ ]:
print('Пример арифметических операций с DataFrame и первичное выравнивание c использованием fill_value значения:')

df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})
print(df1)
print(df2)
print(df1 - df2)
print(df1.sub(df2,fill_value=0))

Пример арифметических операций с DataFrame и первичное выравнивание c использованием fill_value значения:
   A
0  1
1  2
   B
0  3
1  4
    A   B
0 NaN NaN
1 NaN NaN
     A    B
0  1.0 -3.0
1  2.0 -4.0


In [ ]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))
print(df1)
print(df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [ ]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [ ]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

### Операции между ```DataFrame``` и ```Series```

In [ ]:
arr = np.arange(12.).reshape(( 3, 4))
print(arr)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [ ]:
arr[0]

array([0., 1., 2., 3.])

In [ ]:
print('Пример операции укладывания для массивов numpy:')
print(arr - arr[0])

Пример операции укладывания для массивов numpy:
[[0. 0. 0. 0.]
 [4. 4. 4. 4.]
 [8. 8. 8. 8.]]


In [ ]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)), 
                     columns=list('bdе') ,
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'] )
series = frame.iloc[0]

print(frame)
print(series)

          b     d     е
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
b    0.0
d    1.0
е    2.0
Name: Utah, dtype: float64


In [ ]:
print('Пример операции укладывания для массивов DataFrame по строкам:')
print(frame - series)

Пример операции укладывания для массивов DataFrame по строкам:
          b    d    е
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0


In [ ]:
print('Пример операции укладывания для массивов DataFrame по столбцам:')

series = frame['b']
print(frame.sub(series,axis=0))


Пример операции укладывания для массивов DataFrame по столбцам:
          b    d    е
Utah    0.0  1.0  2.0
Ohio    0.0  1.0  2.0
Texas   0.0  1.0  2.0
Oregon  0.0  1.0  2.0


### Применение функций и отображение

In [ ]:
print('Применение функций NumPy к объектам DataFrame:')
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
print(frame)
print(np.abs(frame))

Применение функций NumPy к объектам DataFrame:
               b         d         e
Utah    0.388957 -1.015943 -1.555478
Ohio    0.801085 -2.161697  1.232312
Texas   0.995088  0.443698 -0.375414
Oregon -0.576452 -0.268838 -2.386734
               b         d         e
Utah    0.388957  1.015943  1.555478
Ohio    0.801085  2.161697  1.232312
Texas   0.995088  0.443698  0.375414
Oregon  0.576452  0.268838  2.386734


In [ ]:
print('Применение функций, определенных для одномерных массивов, к каждому столбцу DataFrame:')
f = lambda x: x.max() - x.min()
frame.apply(f)

Применение функций, определенных для одномерных массивов, к каждому столбцу DataFrame:


b    1.571540
d    2.605395
e    3.619046
dtype: float64

In [ ]:
print('Применение той же функции к строке:')
frame.apply(f, axis=1)

Применение той же функции к строке:


Utah      1.944435
Ohio      3.394009
Texas     1.370502
Oregon    2.117895
dtype: float64

In [ ]:
print('Применение функций, возвращающих Series объект:')
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

Применение функций, возвращающих Series объект:


b         d         e
min -0.576452 -2.161697 -2.386734
max  0.995088  0.443698  1.232312

In [ ]:
print('Поэлементрарное применение функций:')
format = lambda x: '%.2f' % x
frame.applymap(format)

Поэлементрарное применение функций:


b      d      e
Utah     0.39  -1.02  -1.56
Ohio     0.80  -2.16   1.23
Texas    1.00   0.44  -0.38
Oregon  -0.58  -0.27  -2.39

In [ ]:
frame.applymap(lambda x: '%.2f' % x)

b      d      e
Utah     0.39  -1.02  -1.56
Ohio     0.80  -2.16   1.23
Texas    1.00   0.44  -0.38
Oregon  -0.58  -0.27  -2.39

## Дополнительные материалы и литература



*   Уэс Маккинли, Python и анализ данных/ Пер. с англ. Слинкин А. А. - М.: ДМК Пресс, 2015. - 482 с.: ил. С. 150